balancer:
  retry-configuration:
    delay: 2000
    max-retries: 5
  cache-configuration:
    enabled: false
    initial-size: 100
    max-size: 1000
    expiration-time: 60000
  servers:
    - url: http://localhost:9000
      enabled: true